import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class UserService {

  //the array of user object containing all the information for a person
  users=[
    { "id": 1, "name": "Abdul Uzair", "age": 29,"gender":"Male", "designation": "Software Engineer", "location": "New York" ,"image":"/assets/man-png-icon-2.jpg","data":"Abdul Uzair is a passionate Software Engineer with expertise in full-stack development. He specializes in working with JavaScript, Angular, and Node.js, building robust and scalable web applications. With a keen interest in AI-driven software, he continuously explores new technologies to enhance development efficiency. Apart from work, Abdul enjoys contributing to open-source projects, mentoring junior developers, and participating in hackathons."},
    { "id": 3, "name": "B.Srihari", "age": 35,"gender":"Male", "designation": "Project Manager", "location": "San Francisco" ,"image":"/assets/man-png-icon-2.jpg","data":"B. Srihari is an accomplished Project Manager with extensive experience in Agile, Scrum, and DevOps practices. He has successfully led multiple teams in the software development and fintech industry, ensuring project delivery within deadlines and budgets. His leadership skills allow him to optimize team performance and resolve roadblocks efficiently. Srihari is also a strong advocate for workplace automation and often speaks at tech conferences on project management methodologies."},
    { "id": 2, "name": "K.Mounika", "age": 42,"gender":"Female", "designation": "HR Manager", "location": "Chicago","image":"/assets/women.png" ,"data":"K. Mounika is a seasoned HR Manager with over 15 years of experience in talent acquisition, employee engagement, and corporate training. She has a strong background in organizational psychology, ensuring a positive work culture and effective workforce management. Mounika is an advocate for diversity and inclusion, implementing policies that foster a more equitable work environment. In her free time, she conducts career counseling sessions and enjoys reading about leadership strategies."},
    { "id": 4, "name": "Muzeebur Rehman", "age": 31,"gender":"Male", "designation": "UI/UX Designer", "location": "Los Angeles","image":"/assets/man-png-icon-2.jpg","data":"Muzeebur Rehman is a creative UI/UX Designer who specializes in human-centered design. With a background in graphic design and front-end development, he crafts user-friendly interfaces that enhance digital experiences. His expertise lies in Figma, Adobe XD, and usability testing, ensuring that web and mobile applications meet high accessibility standards. Muzeebur frequently collaborates with developers to create seamless user interfaces and is a contributor to design communities. In his spare time, he enjoys photography and digital art." },
    { "id": 5, "name": "E.Praveen", "age": 27,"gender":"Male", "designation": "Data Scientist", "location": "Austin","image":"/assets/man-png-icon-2.jpg" ,"data":"E. Praveen is a Data Scientist who specializes in machine learning, big data analytics, and predictive modeling. With a background in statistics and artificial intelligence, he builds algorithms that help companies make data-driven decisions. His expertise includes Python, TensorFlow, and SQL, and he has worked on projects related to customer segmentation, fraud detection, and recommendation systems. Praveen is also an active member of the AI research community and loves experimenting with deep learning models in his free time."},
    { "id": 6, "name": "N.Sai Teja", "age": 38,"gender":"Male", "designation": "Marketing Director", "location": "Seattle","image":"/assets/man-png-icon-2.jpg" ,"data":"N. Sai Teja is an experienced Marketing Director with a proven track record in branding, digital marketing, and business strategy. With a strong understanding of consumer behavior and market trends, he has successfully launched multiple global marketing campaigns that have resulted in high engagement and sales growth. His expertise includes SEO, content marketing, and social media advertising, ensuring that brands maintain a competitive edge. In addition to his corporate role, Sai Teja enjoys mentoring startups and writing blogs on marketing strategies."},
    { "id": 7, "name": "K.Rudrapreeth", "age": 45,"gender":"Male", "designation": "CTO", "location": "Boston","image":"/assets/man-png-icon-2.jpg" ,"data":"K. Rudrapreeth is a visionary CTO (Chief Technology Officer) with over 20 years of experience in software architecture and enterprise solutions. He has led technology transformation initiatives in various industries, including finance, healthcare, and e-commerce. With expertise in cloud computing, cybersecurity, and blockchain, he plays a pivotal role in shaping technology roadmaps for organizations. He actively mentors young tech entrepreneurs and contributes to open-source security projects. In his free time, he enjoys researching the future of AI and quantum computing."},
    { "id": 8, "name": "B.Bhargav Mallik", "age": 33,"gender":"Male", "designation": "DevOps Engineer", "location": "Denver" ,"image":"/assets/man-png-icon-2.jpg","data":"B. Bhargav Mallik is a skilled DevOps Engineer specializing in automation, cloud infrastructure, and CI/CD pipelines. With extensive experience in AWS, Kubernetes, and Docker, he ensures that development and operations teams collaborate seamlessly. His expertise in infrastructure as code (IaC) enables businesses to optimize deployment cycles and improve system scalability. He is passionate about automation scripting and regularly contributes to the DevOps community through blog posts and technical talks. Outside work, he enjoys experimenting with new cloud technologies and cybersecurity trends."}
  ]
  
}
